#!/bin/bash

set -e

export NEXT_PUBLIC_DEPLOY_ENV=${DEPLOY_ENV}
export NEXT_PUBLIC_EDITION=${EDITION}
export NEXT_PUBLIC_API_PREFIX=${CONSOLE_API_URL}/console/api
export NEXT_PUBLIC_PUBLIC_API_PREFIX=${APP_API_URL}/api

export NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
export NEXT_PUBLIC_SITE_ABOUT=${SITE_ABOUT}

export NEXT_PUBLIC_DEPLOY_REGION=${DEPLOY_REGION}
export NEXT_PUBLIC_APP_ERROR_REPLACE_URL_404=${APP_ERROR_REPLACE_URL_404}

pm2 start ./pm2.json --no-daemon
