"""Add quota and expiration to member_invite

Revision ID: 3b46c5f95a53
Revises: 7ae26829e375
Create Date: 2024-07-24 15:39:30.763804

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b46c5f95a53'
down_revision = '7ae26829e375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('expiration', sa.DateTime(), server_default=sa.text("CURRENT_DATE + INTERVAL '1 day'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_invite', schema=None) as batch_op:
        batch_op.drop_column('expiration')
        batch_op.drop_column('quota')

    # ### end Alembic commands ###
