"""empty message

Revision ID: 6054423cf5da
Revises: f95de38dde6a
Create Date: 2024-05-31 07:59:14.367414

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6054423cf5da'
down_revision = 'f95de38dde6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_integrates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unionid', sa.String(length=255), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_integrates', schema=None) as batch_op:
        batch_op.drop_column('unionid')

    # ### end Alembic commands ###
