"""empty message

Revision ID: 7ae26829e375
Revises: 6054423cf5da
Create Date: 2024-06-13 03:03:32.176052

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae26829e375'
down_revision = '6054423cf5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_invite', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
