"""empty message

Revision ID: f95de38dde6a
Revises: 05c256b1d946
Create Date: 2024-05-31 07:22:04.874299

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95de38dde6a'
down_revision = '05c256b1d946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_integrates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=255), server_default='', nullable=True))
        batch_op.add_column(sa.Column('headimgurl', sa.String(length=255), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_integrates', schema=None) as batch_op:
        batch_op.drop_column('headimgurl')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
